### PR TITLE
Change WhatWeDoSection.js to WhatWeDoSection.jsx

### PR DESCRIPTION
**Pull request by rusiruavb**
Previously, WhatWeDoSection component is a .js file. But when I change it to .jsx format it throws an error like this,
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

Actually, the issue was in the **WhatWeDoSection.json** file, because both the functional component name and the JSON file names are the same. I have done some changes and now it's working fine.
@Shehanka @gihanrcg @lwpamihiranga please take a look.

### CODE REVIEW

**Comment by lwpamihiranga** [comment]
nice @rusiruavb. 

additionally, when you are creating the pull request you can link the issue so it will be closed with the merge of the pull request. 🙂
closes #32

**Comment by rusiruavb** [comment]
> nice @rusiruavb.
> 
> additionally, when you are creating the pull request you can link the issue like below so it will be closed with the merge of the pull request. 🙂
> 
> closes #32

Ah.. okay. I have already linked the issue to this pull request

**Review by lwpamihiranga — APPROVED** [review]
LGTM 👍

**Review by gihanrcg — APPROVED** [review]
Great work. I was just about the commit this :D

**Pull request merged**
