### PR TITLE
events card restructured

### PR DESCRIPTION
**Pull request by DInuwan97**

### CODE REVIEW

**Review by gihanrcg — APPROVED** [review]

**Review by gihanrcg — CHANGES_REQUESTED** [review]
Don't we need to have the date ?

**Comment by gihanrcg** [comment]
Can we add the date to the json file as well.?

**Comment by DInuwan97** [comment]
> Don't we need to have the date ?

Yes. It should be in JSON. Will update it afterword's.

**Comment by DInuwan97** [comment]
> Can we add the date to the json file as well.?

I ll do

**Review by gihanrcg — APPROVED** [review]

**Pull request merged**
