### PR TITLE
Introducing Unit Tests

### LINKED ISSUE #25: Introduce JEST unit testing
For this project, there is absolutely no use of unit tests. However, if we practise using unit tests in this project, it will help us a lot in the next big projects. 

We can start with small unit tests to test simple things.
And make it a prerequisite to the pre commit hook

### LINKED ISSUE #41: Unit Test run fails with Error: "TypeError: Cannot read property 'fn' of undefined"
Screenshot 2021-04-13 at 11 33 50

_Originally posted by @Shehanka in https://github.com/ms-club-sliit/msclubwebsite/issues/36#issuecomment-818463817_

### PR DESCRIPTION
**Pull request by lwpamihiranga**
Since there is no logic to write unit tests at the moment I have written some basic smoke test for the currently implemented components. 

@gihanrcg aiye let's discuss any concerns you have or if there are any structural changes you prefer.

I have put the test file into the same directory of the component. we can create put them in `__tests__` folder as well. Let me know what would be best 🙂

fixes #25 
fixes #41

### CODE REVIEW

**Comment by gihanrcg** [comment]
No complaints from me. This looks great :+1:

**Comment by gihanrcg** [comment]
@lwpamihiranga there are some conflicts

**Comment by lwpamihiranga** [comment]
> @lwpamihiranga there are some conflicts

will looking into this shortly aiye

**Comment by lwpamihiranga** [comment]
@gihanrcg I think this is good to go now

**Review by Shehanka — DISMISSED** [review]

**Comment by Shehanka** [comment]
I enabled testing in the GitHub action

**Comment by Shehanka** [comment]
Screenshot 2021-04-13 at 11 33 50

**Comment by lwpamihiranga** [comment]
> I enabled testing in the GitHub action

Nice

**Comment by lwpamihiranga** [comment]
> Screenshot 2021-04-13 at 11 33 50
> 

I will have a look on this

**Comment by lwpamihiranga** [comment]
https://github.com/ms-club-sliit/msclubwebsite/blob/97044d64aaf660a99a9b11e9b5152507afcb0663/src/modules/EventsModule/pastEvents/PastEvents.jsx#L2-L4

`react-owl-carousel` related `jQuery` issue. currently investigating

**Comment by lwpamihiranga** [comment]
@gihanrcg @Shehanka waiting for an approval from one of you 🙂

**Review by gihanrcg — APPROVED** [review]

**Pull request merged**
